#!/usr/bin/env escript
%% -*- erlang -*-

main([InFile, OutFile | BeamFiles]) ->
    Modules = [list_to_atom(filename:basename(F, ".beam")) || F <- BeamFiles],
    {ok, [{application, Application, Properties}]} = file:consult(InFile),
    NewProperties = [case Prop of
                         {modules, _} -> {modules, Modules};
                         OtherProp    -> OtherProp
                     end || Prop <- Properties],
    file:write_file(
      OutFile,
      io_lib:format("~p.~n", [{application, Application, NewProperties}])).
