PACKAGE=rabbitmq-ram-queues
APPNAME=rabbitmq_ram_queues # BUGBUG:  Plugin dev guide may need update?
DEPS=rabbitmq-server
INTERNAL_DEPS=
RUNTIME_DEPS=

include ../include.mk

# BUGBUG:  Hack...  I wouldn't have thought I'd needed this
ebin/$(APPNAME).app:
